### ISSUE TITLE
error[E0658]: deriving `Default` on enums is experimental

### ISSUE THREAD

**Issue by miaomiao1992** [flo-at/rustsnake#2]
#Rust stable MSVC 1.57 

error[E0658]: deriving `Default` on enums is experimental
  --> src\frame_buffer.rs:18:10
   |
18 | #[derive(Default, Clone, PartialEq, Copy)]
   |          ^^^^^^^
   |
   = note: see issue #86985 <https://github.com/rust-lang/rust/issues/86985> for more information
   = note: this error originates in the derive macro `Default` (in Nightly builds, run with -Z macro-backtrace for more info)

**Comment by flo-at** [comment]
Thanks for the report. According to the [stabilization PR](https://github.com/rust-lang/rust/pull/94457) this feature is stable since Rust 1.62. Can you update your Rust and check again, please? It seems to be pretty outdated.

**Comment by miaomiao1992** [comment]
> Thanks for the report. According to the [stabilization PR](https://github.com/rust-lang/rust/pull/94457) this feature is stable since Rust 1.62. Can you update your Rust and check again, please? It seems to be pretty outdated.

thanks, now the issue is solved.
